name: souqna_app
description: "تطبيق سوقنا - منصة سوق تجاري"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/icon_myads.png
    - images/logos/alfaromeo.png
    - images/logos/chery.png
    - images/logos/cupra.png
    - images/logos/dodge.png
    - images/logos/geely.png
    - images/logos/genesis.png
    - images/logos/haval.png
    - images/logos/isuzu.png
    - images/logos/landrover.png
    - images/logos/lexus.png
    - images/logos/lincoln.png
    - images/logos/lotus.png
    - images/logos/mercedes.png
    - images/logos/rover.png
    - images/logos/ssangyong.png
    - images/logos/vinfast.png
    - images/logos/higer.png
    - images/logos/yutong.png
    - images/logos/kinglong.png
    - images/logos/goldendragon.png
    - images/logos/daewoo.png
    - images/logos/setra.png
    - images/logos/hino.png
    - images/logos/sinotruk.png
    - images/logos/shacman.png
    - images/logos/faw.png
    - images/logos/dongfeng.png
    - images/logos/vms.png
    - images/logos/keeway.png
    - images/logos/lifan.png
    - images/logos/bajaj.png
    - images/logos/hero.png
    - images/logos/tvs.png
    - images/logos/sym.png
    - images/logos/haojue.png
    - images/logos/aprilia.png
    - images/logos/benelli.png
    - images/logos/royalenfield.png
    - images/logos/niu.png
    - images/logos/surron.png
    - images/logos/mvagusta.png
    - images/logos/piaggio.png
    - images/logos/kawasaki.png
    - images/logos/yamaha.png
    - images/equipment/forklifts.jpg
    - images/equipment/refrigerators.jpg
    - images/equipment/cranes.jpg
    - images/equipment/concrete.jpg
    - images/equipment/spare_parts.jpg
    - images/equipment/dump_excavators.jpg
